Randomness in Python ::
-------------------------------------------------------------------------------

In [1]:
import random

Part 01::
----------------------------

Use random.choice and range to generate a random integer from 0-9.

In [2]:
random.choice(range(10))

4

What will random.choice(list([1,2,3,4])) produce?

In [4]:
random.choice(list([1,2,3,4]))

1

Which of the following lines of code takes the sum of 10 random integers between 0 and 9?
sum(random.sample(range(10),10))
sum(random.choice(range(10),10))
random.sample_sum(range(10), 10)
sum(random.choice(range(10)) for i in range(10))

In [5]:
sum(random.choice(range(10)) for i in range(10))

53

Part 02 >>
--------------------------------------

What will random.choice(list((1,2,3,4))) do?

In [6]:
random.choice(list((1,2,3,4)))

1

Part 03 >>
----------------------------------------

What does numpy.random.random((5,2,3)) do?

In [7]:
import numpy
numpy.random.random((5,2,3))

array([[[0.92938242, 0.60061016, 0.80662057],
        [0.18791496, 0.70710756, 0.21257424]],

       [[0.71031013, 0.0824486 , 0.24795977],
        [0.07458567, 0.46061037, 0.93377919]],

       [[0.65066402, 0.7855461 , 0.34138858],
        [0.62918088, 0.22554609, 0.7957296 ]],

       [[0.38384274, 0.05325949, 0.20905716],
        [0.50295   , 0.48422642, 0.60712041]],

       [[0.82130072, 0.8524339 , 0.42092802],
        [0.32542901, 0.91930028, 0.35457508]]])

What does numpy.random.normal(1,2,3) do?

In [14]:
x=numpy.random.normal(1,2,3)
print(x)
print(x.std(), x.mean())

[-0.07639392  2.78070689  1.23667099]
1.1676762967639867 1.3136613205590066


What does numpy.random.randint(1,5,(2,3)) do?

In [15]:
numpy.random.randint(1,5,(2,3))

array([[3, 1, 2],
       [2, 4, 4]])

What is the dimension of numpy.sum(numpy.random.randint(1,7,(100,10)), axis=0)?

In [17]:
x=numpy.sum(numpy.random.randint(1,7,(100,10)), axis=0)
print(x.size)

10


Part 04 >> Time
---------------------------------

In [1]:
import time

Consider the following code:

      
start_time = time.clock()
stop_time = time.clock()
stop_time - start_time

    
What does this return?

In [2]:
start_time = time.clock()
stop_time = time.clock()
stop_time - start_time

AttributeError: module 'time' has no attribute 'clock'